### ISSUE TITLE
Turnitin is calling grade_update directly!!

### ISSUE THREAD

**Issue by mhughes2k** [turnitin/moodle-plagiarism_turnitin#141]
We have had strange reports where assignment activities in Moodle had final grades visible in the grade book, whilst blind marking was still in effect.

Looking through the plagiarism plugin code I found in lib.php a call to grade_update() (https://github.com/turnitin/moodle-plagiarism_turnitin/blob/master/lib.php#L1353), which updates the gradebook.

This should not be called directly by the plagiarism plugin because mod assign has **additional** rules that are designed to prevent grades propagating to the gradebook until certain conditions **such as blind marking** have been satisfied.

It really **must** use the library functions in `mod_assign` such as `gradebook_item_update()` which understands these features!

**Comment by mhughes2k** [comment]
In fact the grade coming back from Turnitin (in the case of assignments) should really be updated in to the `assign_grades` table via the `mod_assign::update_grades()` function.

This is again another flaw that really comes down to the fact that **grading** should be done via the plagiarism plugin hooks, that is *not* their purpose and there is a comprehensive mechanism for adding grading methods in **Advanced Grading Methods**.

**Comment by jmcgettrick** [comment]
Fixed in 2016091401.

**Comment by mhughes2k** [comment]
Just checked this and it's not fixed. 

The code in li.php writes to the assign_grades table, fair enough. 

But then to check if the grades can be released it *only* looks at the assign_use_flags table.
This still *doesn't* take in to account the blind marking status of the assignment.

The code calls `assign_grade_item_update `not the `gradebook_item_update()` method **on the assign object**

The `mod_assign::gradebook_item_update()` function makes a call to `is_blind_marking()` which validates the blind marking state

**Comment by mhughes2k** [comment]
Further investigation has the grade being updated on the master version

But the "old" version that we have running currently which is v2016072601 (which I can't find in Github) *doesn't* demonstrate this behaviour!

Is this a possible regression that's crept in!
