### ISSUE TITLE
PHPUnit test failing with Moodle 31

### ISSUE THREAD

**Issue by roperto** [turnitin/moodle-plagiarism_turnitin#179]
Has anyone else run into this issue?

When I run core Moodle 31 PHPUnit tests, one of them fails if I have this plugin installed.

I've isolated the problem in the lib, where it finds the supported modules based on the file (classes/modules) system then tries to fetch the ID in the database. 

Because it cannot find the module in the DB (returns false), if fails when trying go get the $module->id.

I wrote a test reproducing the behaviour and a proposed solution; however, someone who has better understanding of this plugin could propose a better solution.

Cheers,

Daniel

**Comment by danmarsden** [comment]
This is a pretty major issue for us... we run these tests automatically on all our clients codebases.

 It might be worthwhile for the Turnitin team to implement travis-ci checks directly within github to help prevent this stuff from happening.
There's a good post on how to add support here:
https://moodle.org/mod/forum/discuss.php?d=323384

but it's really just copying a .travis.yml file, adjusting it as needed and going to travis-ci.org and switching it on.

**Comment by alexumn** [comment]
A quick note: https://github.com/turnitin/moodle-plagiarism_turnitin/pull/188/ (created by one of our Moodle developers, Travis Noll) addresses this specific issue as well. Let this be another vote to implement travis-ci and Behat tests in this plugin.

**Comment by micaherne** [comment]
We're also seeing this on Moodle 3.0:

1) tool_uploadcourse_course_testcase::test_reset
Unexpected debugging() call detected.
Debugging: Exception encountered in event observer 'plagiarism_plugin_turnitin::course_reset': Trying to get property of non-object
* line 328 of /plagiarism/turnitin/lib.php: call to PHPUnit_Util_ErrorHandler::handleError()
* line ? of unknownfile: call to plagiarism_plugin_turnitin::course_reset()
* line 155 of /lib/classes/event/manager.php: call to call_user_func()
* line 75 of /lib/classes/event/manager.php: call to core\event\manager::process_buffers()
* line 804 of /lib/classes/event/base.php: call to core\event\manager::dispatch()
* line 5306 of /lib/moodlelib.php: call to core\event\base->trigger()
* line 902 of /admin/tool/uploadcourse/classes/course.php: call to reset_course_userdata()
* line 748 of /admin/tool/uploadcourse/classes/course.php: call to tool_uploadcourse_course->reset()
* line 827 of /admin/tool/uploadcourse/tests/course_test.php: call to tool_uploadcourse_course->proceed()
* line ? of unknownfile: call to tool_uploadcourse_course_testcase->test_reset()
* line 908 of /var/lib/jenkins/workspace/r-build/master/vendor/phpunit/phpunit/src/Framework/TestCase.php: call to ReflectionMethod->invokeArgs()
* line 768 of /var/lib/jenkins/workspace/r-build/master/vendor/phpunit/phpunit/src/Framework/TestCase.php: call to PHPUnit_Framework_TestCase->runTest()
* line 80 of /lib/phpunit/classes/advanced_testcase.php: call to PHPUnit_Framework_TestCase->runBare()
* line 612 of /var/lib/jenkins/workspace/r-build/master/vendor/phpunit/phpunit/src/Framework/TestResult.php: call to advanced_testcase->runBare()
* line 724 of /var/lib/jenkins/workspace/r-build/master/vendor/phpunit/phpunit/src/Framework/TestCase.php: call to PHPUnit_Framework_TestResult->run()
* line 747 of /var/lib/jenkins/workspace/r-build/master/vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit_Framework_TestCase->run()
* line 747 of /var/lib/jenkins/workspace/r-build/master/vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit_Framework_TestSuite->run()
* line 747 of /var/lib/jenkins/workspace/r-build/master/vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit_Framework_TestSuite->run()
* line 440 of /var/lib/jenkins/workspace/r-build/master/vendor/phpunit/phpunit/src/TextUI/TestRunner.php: call to PHPUnit_Framework_TestSuite->run()
* line 149 of /var/lib/jenkins/workspace/r-build/master/vendor/phpunit/phpunit/src/TextUI/Command.php: call to PHPUnit_TextUI_TestRunner->doRun()
* line 100 of /var/lib/jenkins/workspace/r-build/master/vendor/phpunit/phpunit/src/TextUI/Command.php: call to PHPUnit_TextUI_Command->run()
* line 47 of /var/lib/jenkins/workspace/r-build/master/vendor/phpunit/phpunit/phpunit: call to PHPUnit_TextUI_Command::main()
Debugging: Exception encountered in event observer 'plagiarism_plugin_turnitin::course_reset': Trying to get property of non-object
* line 328 of /plagiarism/turnitin/lib.php: call to PHPUnit_Util_ErrorHandler::handleError()
* line ? of unknownfile: call to plagiarism_plugin_turnitin::course_reset()
* line 155 of /lib/classes/event/manager.php: call to call_user_func()
* line 75 of /lib/classes/event/manager.php: call to core\event\manager::process_buffers()
* line 804 of /lib/classes/event/base.php: call to core\event\manager::dispatch()
* line 5306 of /lib/moodlelib.php: call to core\event\base->trigger()
* line 902 of /admin/tool/uploadcourse/classes/course.php: call to reset_course_userdata()
* line 748 of /admin/tool/uploadcourse/classes/course.php: call to tool_uploadcourse_course->reset()
* line 843 of /admin/tool/uploadcourse/tests/course_test.php: call to tool_uploadcourse_course->proceed()
* line ? of unknownfile: call to tool_uploadcourse_course_testcase->test_reset()
* line 908 of /var/lib/jenkins/workspace/r-build/master/vendor/phpunit/phpunit/src/Framework/TestCase.php: call to ReflectionMethod->invokeArgs()
* line 768 of /var/lib/jenkins/workspace/r-build/master/vendor/phpunit/phpunit/src/Framework/TestCase.php: call to PHPUnit_Framework_TestCase->runTest()
* line 80 of /lib/phpunit/classes/advanced_testcase.php: call to PHPUnit_Framework_TestCase->runBare()
* line 612 of /var/lib/jenkins/workspace/r-build/master/vendor/phpunit/phpunit/src/Framework/TestResult.php: call to advanced_testcase->runBare()
* line 724 of /var/lib/jenkins/workspace/r-build/master/vendor/phpunit/phpunit/src/Framework/TestCase.php: call to PHPUnit_Framework_TestResult->run()
* line 747 of /var/lib/jenkins/workspace/r-build/master/vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit_Framework_TestCase->run()
* line 747 of /var/lib/jenkins/workspace/r-build/master/vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit_Framework_TestSuite->run()
* line 747 of /var/lib/jenkins/workspace/r-build/master/vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit_Framework_TestSuite->run()
* line 440 of /var/lib/jenkins/workspace/r-build/master/vendor/phpunit/phpunit/src/TextUI/TestRunner.php: call to PHPUnit_Framework_TestSuite->run()
* line 149 of /var/lib/jenkins/workspace/r-build/master/vendor/phpunit/phpunit/src/TextUI/Command.php: call to PHPUnit_TextUI_TestRunner->doRun()
* line 100 of /var/lib/jenkins/workspace/r-build/master/vendor/phpunit/phpunit/src/TextUI/Command.php: call to PHPUnit_TextUI_Command->run()
* line 47 of /var/lib/jenkins/workspace/r-build/master/vendor/phpunit/phpunit/phpunit: call to PHPUnit_TextUI_Command::main()

**Comment by azrek** [comment]
It's still an issue in Moodle 3.2 with failing unit tests (same as the Moodle 3.0 unit test failing above).

It appears to have been fixed in the development branch but not yet merged in the master branch.

https://github.com/catalyst/moodle-plagiarism_turnitin/commit/1ebfdef9d5b13ce3b24b3b3b7e5277f9f8b8081c

**Comment by dwinn** [comment]
We plan to have this issue fixed in the next release.

Moodle 3.2 support is another issue however - we don't support it in the latest release but we will be supporting 3.2 once we've fully tested it - that too will require a release.

**Comment by dwinn** [comment]
Hi @roperto ,

This has been fixed in the latest release v2015012501

**Comment by danmarsden** [comment]
@dwinn - did you fix the course reset failure shown above too? - I am still seeing this on the latest build.

**Comment by dwinn** [comment]
Hi @danmarsden,

You are correct, I have just ran the tests tool_uploadcourse_course_testcase and I am still getting an error. The error is different to the one posted here however. Part of the stack track:

`Debugging: Exception encountered in event observer 'plagiarism_plugin_turnitin::course_reset': Undefined index: reset_assign_submissions
* line 304 of /plagiarism/turnitin/lib.php: call to PHPUnit_Util_ErrorHandler::handleError()`

We will get this fixed.
